/*
  * Leight weight variant of the gcc's gcov-library.
  *
  * This code is based on gcc_3_4.c  from gcc 4.7 and the Linux kernel code
  * kernel/gcov.
  *
  * This code provides functions to handle gcc's profiling data format
  * introduced with gcc 4.7. It basically uses the convert_to_gcda function to
  * generate the .gcda files information upon application completion, and dump
  * it on the serial console.
  *
  * Special thanks to
  *   Aitorvs: https://github.com/aitorvs/tiny-coverage
  *   Tejainece: https://github.com/tejainece/tcov
  *   Erich Styger: https://mcuoneclipse.com
  *
 */

#include <stdio.h>
#include <unistd.h>
#include <stdint.h>
#include <malloc.h>
#include <errno.h>
#include <fcntl.h>
#include "coverage.h"

#if __GNUC__ == 5 && __GNUC_MINOR__ >= 1
#define GCOV_COUNTERS                   10
#elif __GNUC__ == 4 && __GNUC_MINOR__ >= 9
#define GCOV_COUNTERS                   9
#else
#define GCOV_COUNTERS                   8
#endif

#if BITS_PER_LONG >= 64
typedef long gcov_type;
#else
typedef long long gcov_type;
#endif

#define GCOV_TAG_FUNCTION_LENGTH  3
#define GCOV_DATA_MAGIC   ((unsigned int) 0x67636461)
#define GCOV_TAG_FUNCTION ((unsigned int) 0x01000000)
#define GCOV_TAG_COUNTER_BASE ((unsigned int) 0x01a10000)
#define GCOV_TAG_FOR_COUNTER(count)         \
(GCOV_TAG_COUNTER_BASE + ((unsigned int) (count) << 17))

/**Information about counters for a single function
 *
 * This data is generated by gcc during compilation and doesn't change
 *  at run-time with the exception of the values array.
 */
struct gcov_ctr_info {
  unsigned int num;   // number of counter values for this type
  gcov_type *values;  // array of counter values for this type
};

/**
 * Profiling meta data per function
 *
 * This data is generated by gcc during compilation and doesn't change
 * at run-time.
 *
 * Information about a single function.  This uses the trailing array
 * idiom. The number of counters is determined from the merge pointer
 * array in gcov_info.  The key is used to detect which of a set of
 * comdat functions was selected -- it points to the gcov_info object
 * of the object file containing the selected comdat function.
 */
struct gcov_fn_info {
  const struct gcov_info *key;    // comdat key
  unsigned int ident;             // unique ident of function
  unsigned int lineno_checksum;   // function lineo_checksum
  unsigned int cfg_checksum;      // function cfg checksum
  struct gcov_ctr_info ctrs[0];   // instrumented counters
};

/** Profiling data per object file
 *
 * This data is generated by gcc during compilation and doesn't change
 * at run-time with the exception of the next pointer. */
struct gcov_info {
  unsigned int version;               // Gcov version (same as GCC version)
  struct gcov_info *next;             // List head for a singly-linked list
  unsigned int stamp;                 // Uniquifying time stamp
  const char *filename;               // Name of the associated gcda data file
  void (*merge[GCOV_COUNTERS])(gcov_type *, unsigned int);  // merge functions
                                                            // null for unused
  unsigned int n_functions;           // number of instrumented functions
  struct gcov_fn_info **functions;    // function information

};

static struct gcov_info *gcov_info_head;

/**
 * Is called by gcc-generated constructor code for each object file compiled
 * with -fprofile-arcs.
 * @param info
 */
void __gcov_init(struct gcov_info *info) {
  info->next = gcov_info_head;
  gcov_info_head = info;
}

void __gcov_merge_add(gcov_type *counters, unsigned int n_counters) {
  /* Unused. */
}

/**
 * store_gcov_u64 - store 64 bit number in gcov format to buffer
 * @buffer: target buffer or NULL
 * @off: offset into the buffer
 * @v: value to be stored
 *
 * Number format defined by gcc: numbers are recorded in the 32 bit
 * unsigned binary form of the endianness of the machine generating the
 * file. 64 bit numbers are stored as two 32 bit numbers, the low part
 * first. Returns the number of bytes stored. If @buffer is %NULL, doesn't store
 * anything.
 */
static size_t store_gcov_u64(void *buffer, size_t off, uint64_t v) {
  uint32_t *data;
  if (buffer) {
    data = buffer + off;
    data[0] = (v & 0xffffffffUL);
    data[1] = (v >> 32);
  }
  return sizeof(*data) * 2;
}

/**
 * store_gcov_u32 - store 32 bit number in gcov format to buffer
 * @buffer: target buffer or NULL
 * @off: offset into the buffer
 * @v: value to be stored
 *
 * Number format defined by gcc: numbers are recorded in the 32 bit
 * unsigned binary form of the endianness of the machine generating the
 * file. Returns the number of bytes stored. If @buffer is %NULL, doesn't
 * store anything.
 */
static size_t store_gcov_u32(void *buffer, size_t off, uint32_t v) {
  uint32_t *data;
  if (buffer) {
    data = buffer + off;
    *data = v;
  }
  return sizeof(*data);
}

/**
 * Determine whether a counter is active. Doesn't change at run-time.
 */
static int counter_active(struct gcov_info *info, unsigned int type) {
  return info->merge[type] ? 1 : 0;
}

/**
 * convert_to_gcda - convert profiling data set to gcda file format
 * @buffer: the buffer to store file data or %NULL if no data should be stored
 * @info: profiling data set to be converted
 *
 * Returns the number of bytes that were/would have been stored into the buffer.
 */
size_t convert_to_gcda(uint8_t *buffer, struct gcov_info *info) {
  struct gcov_fn_info *fi_ptr;
  struct gcov_ctr_info *ci_ptr;
  unsigned int fi_idx;
  unsigned int ct_idx;
  unsigned int cv_idx;
  size_t pos = 0;

  /* File header. */
  pos += store_gcov_u32(buffer, pos, GCOV_DATA_MAGIC);
  pos += store_gcov_u32(buffer, pos, info->version);
  pos += store_gcov_u32(buffer, pos, info->stamp);

  for (fi_idx = 0; fi_idx < info->n_functions; fi_idx++) {
    fi_ptr = info->functions[fi_idx];

    /* Function record. */
    pos += store_gcov_u32(buffer, pos, GCOV_TAG_FUNCTION);
    pos += store_gcov_u32(buffer, pos, GCOV_TAG_FUNCTION_LENGTH);
    pos += store_gcov_u32(buffer, pos, fi_ptr->ident);
    pos += store_gcov_u32(buffer, pos, fi_ptr->lineno_checksum);
    pos += store_gcov_u32(buffer, pos, fi_ptr->cfg_checksum);

    ci_ptr = fi_ptr->ctrs;

    for (ct_idx = 0; ct_idx < GCOV_COUNTERS; ct_idx++) {
      if (!counter_active(info, ct_idx))
        continue;

      /* Counter record. */
      pos += store_gcov_u32(buffer, pos, GCOV_TAG_FOR_COUNTER(ct_idx));
      pos += store_gcov_u32(buffer, pos, ci_ptr->num * 2);

      for (cv_idx = 0; cv_idx < ci_ptr->num; cv_idx++) {
        pos += store_gcov_u64(buffer, pos, ci_ptr->values[cv_idx]);
      }

      ci_ptr++;
    }
  }
  return pos;
}

/**
 * Dumps the coverage data to file system
 * @return Zero on success
 * @note Using the subs in syscalls.c will use a kind of leight weight filesystem which uses the serial interface to transfer the coverage data from the embedded platform to a host computer.
 */
int coverage_dump() {
  struct gcov_info *tmp = gcov_info_head;
  while (tmp) {
    int f, ret;
    uint8_t *buffer;
    size_t size = convert_to_gcda(NULL, tmp);
    buffer = (uint8_t*) malloc(size);
    if (!buffer)
      return -ENOMEM;
    convert_to_gcda(buffer, tmp);

    f = open(tmp->filename, 0);  // Calls _open in syscalls
    ret = write(f, buffer, size);   // Calls _write in syscalls
    if(ret != size)
      return ret;

    free(buffer);
    tmp = tmp->next;
  }
  return 0;
}

